# Generated by Django 4.0.3 on 2024-02-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190105_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
